spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-tbt.cjqic66ekxz3.ap-northeast-2.rds.amazonaws.com:5432/TBT
    username: root
    password: wodn02120212


jwt:
  secret: asdfasdfqwehjafsdjkasfdasdfasdfasdfasfdasdfasfdasdfasdfadsf
  expiration_time: 86400000